# Foundry Configuration File
# See more config options at: https://github.com/gakonst/foundry/tree/master/config

[profile.default]
verbosity = 3
ffi = true
fuzz_runs = 1000
optimizer = true
optimizer_runs = 10000
remappings = [
    'solmate/=lib/solmate/src/',
    'openzeppelin-contracts/=lib/openzeppelin-contracts/',
    'forge-std/=lib/forge-std/src/',
]

# extends default options
[profile.intense]
fuzz-runs = 10_000
cache = false
force = true

[fmt]
line_length = 128